import { MouseEventHandler, useState } from "react";
import Head from "next/head";
import { LazyImage } from "../components/RandomCapy";

const generateId = () => Math.random().toString(36).substring(2, 9);
type ImageItem = { id: string; url: string };

export default function Home() {
  const max = 739;
  const min = 1;
  const random = () => Math.floor(Math.random() * (max - min) + min);

  const [images, setImages] = useState<Array<ImageItem>>([]);

  const addNewCapy: MouseEventHandler<HTMLButtonElement> = (event) => {
    event.preventDefault();
    const newImageItem: ImageItem = {
      id: generateId(),
      url: `https://api.capy.lol/v1/capybara/${random()}`,
    };
    setImages([...images, newImageItem]);
  };
  return (
    <>
      <Head>
        <title>Typescript/React Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <button
          className="p-3 mt-6 pointer text-purple-700 hover:text-white border border-purple-700 hover:bg-purple-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-purple-400 dark:text-purple-400 dark:hover:text-white dark:hover:bg-purple-500 dark:focus:ring-purple-900"
          onClick={addNewCapy}
        >
          Add new Capy
        </button>
        {images.map(({ id, url }) => (
          <div key={id} className="p-4">
            <LazyImage
              width={320}
              height="auto"
              src={url}
              className="rounded bg-gray-300"
            />
          </div>
        ))}
      </main>
    </>
  );
}
